def JOBID= 'CHT-AWSCli'

import org.apache.commons.lang.StringEscapeUtils
import groovy.transform.Field
@Field def OSCODE= 'amzn2'
@Field def OSNAME= 'amazon'
@Field def DEFAULTSSHKEY= 'prod-Tokyo-key-001'
@Field def sshURI= 'ec2-user@10.193.18.80'

properties([
    parameters([
        booleanParam(name: 'dryRun', defaultValue: false),
        booleanParam(name: 'doClean', defaultValue: false),

        string(name: 'AwsSecretSet', trim: true, defaultValue: "ec2-user@10.193.18.80 AKIA4C3ED3SKZ7R64A6S rIqeFsuCQoqv2v8XNskNROjByjFvufnuuH8Sswq9 ap-northeast-1"),
        string(name: 'CREDID', trim: true, defaultValue: 'prod-Tokyo-key-001'),
        choice(name: 'TYPES', choices: ['t2.micro', 't2.medium', 't2.large', 't2.xlarge'], description: 'https://aws.amazon.com/ec2/instance-types/'),
        string(name: 'VM_NAME', trim: true, defaultValue: '', description: '如不給就是: job-NUMBER'),

        choice(name: 'REGION', choices: ['ap-northeast-1', 'us-west-1']),
        string(name: 'IMAGEID', trim: true, defaultValue: 'ami-072bfb8ae2c884cc4', description: 'ap-northeast-1'),

        string(name: 'SUBNETID', trim: true, defaultValue: "subnet-04cc6b10809c462fc", description: 'cht: subnet-04cc6b10809c462fc'),
        string(name: 'SECURITYGROUP', trim: true, defaultValue: "sg-0bbd4cb18dd132a71 sg-0e602d76c5a68de16", description: 'cht: sg-0bbd4cb18dd132a71 sg-0e602d76c5a68de16'),
        choice(name: 'IPTYPE', choices: ['PrivateIpAddress', 'PublicIpAddress']),
    ])
])

(sshURI, AccessKeyId, SecretAccessKey) = AwsSecretSet.trim().split(' ')
def KEYNAME= CREDID.toString()
sshURI= StringEscapeUtils.unescapeHtml(sshURI)

def VM_NAME= JOBID.toLowerCase()

node('master') {
    stage("Create AWSCli"){
        jobBuild = build job: 'AWSCli', parameters: [
            string(name: 'sshURI', value: sshURI),
            string(name: 'CREDID', value: CREDID ),
            string(name: 'KEYNAME', value: KEYNAME),
            
            string(name: 'TYPES', value: TYPES),
            string(name: 'IMAGEID', value: "ami-072bfb8ae2c884cc4" ),
            string(name: 'REGION', value: REGION ),
            string(name: 'VM_NAME', value: "${VM_NAME}-${BUILD_NUMBER}"),
            
            string(name: 'SUBNETID', value: SUBNETID ),
            string(name: 'SECURITYGROUP', value: SECURITYGROUP ),
            string(name: 'IPTYPE', value: IPTYPE ),

            string(name: 'AccessKeyId', value: AccessKeyId),
            string(name: 'SecretAccessKey', value: SecretAccessKey), 
            string(name: 'IPTYPE', value: "PublicIpAddress" ),
        ]
        def vars= jobBuild.getBuildVariables()
        NewVMIP= vars['NewVMIP']
        NewSSHUSER= vars['NewSSHUSER']
    }
    echo """***
          NewVMIP: ${NewVMIP}
       NewSSHUSER: ${NewSSHUSER}
        NewSshUri: ${NewSSHUSER}@${NewVMIP}
            TYPES: ${TYPES}
           REGION: ${REGION}
    """
}